// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKnIfRD-3v6kJegNkWmYnrJx-WGKIrZVU',
    appId: '1:1074774540816:web:e0e6d5aac51b5a1e360095',
    messagingSenderId: '1074774540816',
    projectId: 'app-travell',
    authDomain: 'app-travell.firebaseapp.com',
    storageBucket: 'app-travell.firebasestorage.app',
    measurementId: 'G-TRXTF12ZGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUHTqK0M0pf8nxp-IpSplTB024O3cmh_w',
    appId: '1:1074774540816:android:002dc6d9760c1312360095',
    messagingSenderId: '1074774540816',
    projectId: 'app-travell',
    storageBucket: 'app-travell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHZ0EeB22dHvCP8mWViePofpYerobxpKg',
    appId: '1:1074774540816:ios:2f395365532c96e6360095',
    messagingSenderId: '1074774540816',
    projectId: 'app-travell',
    storageBucket: 'app-travell.firebasestorage.app',
    iosBundleId: 'com.example.travellApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHZ0EeB22dHvCP8mWViePofpYerobxpKg',
    appId: '1:1074774540816:ios:2f395365532c96e6360095',
    messagingSenderId: '1074774540816',
    projectId: 'app-travell',
    storageBucket: 'app-travell.firebasestorage.app',
    iosBundleId: 'com.example.travellApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKnIfRD-3v6kJegNkWmYnrJx-WGKIrZVU',
    appId: '1:1074774540816:web:041c106a6a55bea0360095',
    messagingSenderId: '1074774540816',
    projectId: 'app-travell',
    authDomain: 'app-travell.firebaseapp.com',
    storageBucket: 'app-travell.firebasestorage.app',
    measurementId: 'G-LVESK26640',
  );

}